version: '3'

services:
  site:
    build:
      context: docker
      dockerfile: nginx.dockerfile
    container_name: nginx-rocketcontent
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./storage/logs/xdebug.log:/var/log/xdebug.log
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql-rocketcontent
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: production
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  php:
    build:
      context: docker
      dockerfile: php.dockerfile
    container_name: php-rocketcontent
    volumes:
      - .:/var/www/html
      - ./docker/etc/resolv.conf:/etc/resolv.conf
    ports:
      - "9000:9000"
    networks:
      - laravel

  selenium:
    image: 'selenium/standalone-chrome:3.11.0-antimony'
    container_name: selenium-rocketcontent
    depends_on:
      - php
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - laravel
    
  redis:
    image: "redis:alpine"
    container_name: redis-rocketcontent
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis-data:/var/lib/redis
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - laravel

networks:
  laravel: